
# Задание на повторение материала


In [60]:
import pandas as pd
import numpy as np

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [61]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [62]:
a1 = a.reshape(12, 1)
a2 = a.reshape(3, 4)
a3 = a.reshape(4, 3)
a4 = a.reshape(2, 6)
a5 = a.reshape(6, 2)
a1, a2, a3, a4, a5

(array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]))

3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк)

In [63]:
a1 = a.reshape(12, -1)
a2 = a.reshape(3, -1)
a3 = a.reshape(-1, 3)
a4 = a.reshape(2, -1)
a5 = a.reshape(-1, 2)
a1, a2, a3, a4, a5

(array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]))

4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [64]:
# Нет. Он будет двумерный из 12 строк.
# Каждый столбец будет так же списком
a1

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.


In [65]:
x = np.random.normal(loc=0.0, scale=1.0, size=(3, 4)) #loc и scale можно было опустить. Это значения по умолчанию
x_f = x.flatten(order='F') # Сначала столбцы, потом строки
x, x_f

(array([[-0.46341769, -0.46572975,  0.24196227, -1.91328024],
        [-1.72491783, -0.56228753, -1.01283112,  0.31424733],
        [-0.90802408, -1.4123037 ,  1.46564877, -0.2257763 ]]),
 array([-0.46341769, -1.72491783, -0.90802408, -0.46572975, -0.56228753,
        -1.4123037 ,  0.24196227, -1.01283112,  1.46564877, -1.91328024,
         0.31424733, -0.2257763 ]))

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [66]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?


In [67]:
b = np.arange(20, 1, -2)
b
# Тут я видимо не понял соль задания. 

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.


In [68]:
a = np.zeros((2,2))
b = np.ones((3, 2))
c = np.vstack((a, b))
c, c.size

(array([[0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]),
 10)

9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.  
Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов.  
Получить матрицу At путем транспонирования матрицы A.  
Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. 
Какой размер имеет матрица B?  
Получится ли вычислить обратную матрицу для матрицы B и почему?  


In [69]:
a = np.arange(0, 12)
A = a.reshape(4, 3)
At = A.T
B = A.dot(At)
B.shape, np.linalg.det(B)
# Не существует обратной матрицы, т.к. определитель = 0

((4, 4), 1.705863559291837e-29)

10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.


In [70]:
np.random.seed(42)
# За выбор числа отдельное спасибо :)

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 


In [71]:
c = np.random.randint(0, 16, 16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

12. Поменяйте его форму так, чтобы получилась квадратная матрица C.  
Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. 
Вычислите определитель, ранг и обратную матрицу D_inv для D.


In [72]:
C = c.reshape(4, 4)
D = B + 10 * C
D_inv = np.linalg.inv(D)
np.linalg.det(D), np.linalg.matrix_rank(D), D_inv

(-28512000.000000045,
 4,
 array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
        [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
        [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
        [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]]))

13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице.  
Убедитесь, что в матрице D_inv остались только нули и единицы. 
С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  
Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.


In [73]:
D_inv = np.where(D_inv<0, 0,1)
D_inv

array([[1, 1, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [1, 0, 1, 0]])

In [74]:
E = np.where(D_inv==1, B, C)
E

array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])